/*
 * WOSynergy_Version.h
 * WOSynergy
 *
 * Copyright 2007-present Greg Hurrell. All rights reserved.
 *
 * Do not edit this file: it is automatically updated each build via a script
 */

/* Some of the information formerly stored in this file is now kept elsewhere to keep gratuitous changes out of the repository. */
#include "com.wincent.buildtools.gitrev.h"

/* START: Auto-updated macro definitions */

#define WO_COPYRIGHT_YEAR           2002-2011

/* END: Auto-updated macro definitons */

/*!

The publicly visible "marketing" version, updated manually.

\bug Must perform a "Clean" or "Clean All" in order for changes to this macro to be picked up by the UpdateBuildVersionNumbers.sh script.

*/
#define WO_INFO_PLIST_VERSION       4.5.2+

/*! Stringification macro. Turns macro EXAMPLE into string "EXAMPLE". So named so as to avoid clashing with the WO_STRINGIFY macro in WOCommon. */
#define WO_SYNERGY_STRINGIFY(var)   #var

/*! Double-stringification macro. Turns macro EXAMPLE into string "contents of EXAMPLE macro after expansion". */
#define WO_STRINGIFY_TWICE(var)     WO_SYNERGY_STRINGIFY(var)

#define WO_BUILDNUMBER_STRING       WO_STRINGIFY_TWICE(WO_BUILDNUMBER)
#define WO_MARKETINGVERSION         WO_STRINGIFY_TWICE(WO_INFO_PLIST_VERSION)

#define WO_COPYRIGHT_YEAR_STRING    WO_STRINGIFY_TWICE(WO_COPYRIGHT_YEAR)
#define WO_COPYRIGHT                "Copyright " WO_COPYRIGHT_YEAR_STRING " Greg Hurrell"

/*! Make what(1) produce meaningful output. Defines a tagged string accesible via "rcsid_tag". The "used" attribute prevents the linker from removing the symbol during dead code stripping. */
#define WO_TAGGED_RCSID(msg, tag) \
        static const char *const rcsid_ ## tag[] __attribute__((used)) = { (char *)rcsid_ ## tag, "\100(#)" msg }

/*! Convenience macro for accessing a string previously created with WO_TAGGED_RCSID. */
#define WO_RCSID_STRING(tag) (rcsid_ ## tag[1] + 4)

#ifndef WO_PREPROCESSING_FOR_INFO_PLIST

WO_TAGGED_RCSID("Build date: " WO_BUILDDATE, builddate);
WO_TAGGED_RCSID("Build number: " WO_BUILDNUMBER_STRING, build);

#if defined(__ppc__)
WO_TAGGED_RCSID("Architecture: PowerPC (ppc)", architecture);
#elif defined(__ppc64__)
WO_TAGGED_RCSID("Architecture: PowerPC (ppc64)", architecture);
#elif defined(__i386__)
WO_TAGGED_RCSID("Architecture: Intel (i386)", architecture);
#elif defined(__x86_64__)
WO_TAGGED_RCSID("Architecture: Intel (x86_64)", architecture);
#endif

WO_TAGGED_RCSID(WO_COPYRIGHT, copyright);
WO_TAGGED_RCSID("Version: " WO_MARKETINGVERSION, version);
WO_TAGGED_RCSID("Synergy", productname);

#endif /* WO_PREPROCESSING_FOR_INFO_PLIST */
